format = """
[ 󰣇 ](fg:#FFFFFF)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
$character"""

[directory]
style = "fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#555555"
format = '[[ $symbol $branch ](fg:#FFFFFF bg:#555555)]($style)'

[git_status]
style = "bg:#555555"
format = '[[($all_status$ahead_behind )](fg:#FFFFFF bg:#555555)]($style)'

[nodejs]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#FFFFFF bg:#333333)]($style)'

[rust]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#FFFFFF bg:#333333)]($style)'

[golang]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#FFFFFF bg:#333333)]($style)'

[php]
symbol = ""
style = "bg:#333333"
format = '[[ $symbol ($version) ](fg:#FFFFFF bg:#333333)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#111111"
format = '[[  $time ](fg:#FFFFFF bg:#111111)]($style)'
